### ISSUE TITLE
Error: Corrupted zip : can't find end of central directory

### ISSUE THREAD

**Issue by parthasharathi** [download13/xlsx-to-row-sheets#1]
I am directly passing xlsxFileBuffer value with out using fs reader functionality.

```
xlsxToRowSheets(xlsxFileBuffer, function(err, sheets) {
     console.log(sheets)
 });
```

in this case I am getting this Error: Corrupted zip : can't find end of central directory

**Comment by download13** [comment]
Can you post a link to the file you get the error on?

**Comment by parthasharathi** [comment]
I face these issues because of below problem
1. passed a stream (xlsxFileBuffer) value it throws error instead of this I convert the stream to buffer then issue is solved
2. Before it updated to .xls file I tried to open the file so its throw the  Error as: Corrupted zip

**Comment by download13** [comment]
This library is just a convenience layer on top of [xlsx](https://github.com/SheetJS/js-xlsx) and I'm not sure if xlsx supports taking streams through it's read function. You'd have to check their documentation.

Also, were you trying to open a .xls file or a .xlsx file? I think [xlsx](https://github.com/SheetJS/js-xlsx) might only support .xlsx files.

**Comment by parthasharathi** [comment]
It supporting both file xlsx as well as xls. Thanks for your reply.

**Comment by parthasharathi** [comment]
Hi

**Comment by download13** [comment]
I stepped through the code and the xlsx module is the one returning nothing so I'm going to guess the error is in there.

Since it can't be fixed here I'm going to close this issue, but you can open an issue on the xlsx repo and see if they can find the problem.
